app.name=PULSE Desktop JavaFX
app.web.root=..
app.web.base-url=http://127.0.0.1:8000
verify.email.lifetime.seconds=86400
reset.password.lifetime.seconds=3600

# By default this matches the Symfony .env file in your web project.
db.host=127.0.0.1
db.port=3306
db.name=pulsedb
db.user=root
db.password=
db.params=useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
